// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: sdfs_server.proto

package sdfs_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Chunk    []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *PutInput) Reset() {
	*x = PutInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInput) ProtoMessage() {}

func (x *PutInput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInput.ProtoReflect.Descriptor instead.
func (*PutInput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{0}
}

func (x *PutInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PutInput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PutOutput) Reset() {
	*x = PutOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOutput) ProtoMessage() {}

func (x *PutOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOutput.ProtoReflect.Descriptor instead.
func (*PutOutput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{1}
}

func (x *PutOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *DeleteInput) Reset() {
	*x = DeleteInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInput) ProtoMessage() {}

func (x *DeleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInput.ProtoReflect.Descriptor instead.
func (*DeleteInput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteOutput) Reset() {
	*x = DeleteOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOutput) ProtoMessage() {}

func (x *DeleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOutput.ProtoReflect.Descriptor instead.
func (*DeleteOutput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *GetInput) Reset() {
	*x = GetInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInput) ProtoMessage() {}

func (x *GetInput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInput.ProtoReflect.Descriptor instead.
func (*GetInput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *GetOutput) Reset() {
	*x = GetOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutput) ProtoMessage() {}

func (x *GetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutput.ProtoReflect.Descriptor instead.
func (*GetOutput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetOutput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type LsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LsInput) Reset() {
	*x = LsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsInput) ProtoMessage() {}

func (x *LsInput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsInput.ProtoReflect.Descriptor instead.
func (*LsInput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{6}
}

type LsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOfMachines []string `protobuf:"bytes,1,rep,name=listOfMachines,proto3" json:"listOfMachines,omitempty"`
}

func (x *LsOutput) Reset() {
	*x = LsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsOutput) ProtoMessage() {}

func (x *LsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsOutput.ProtoReflect.Descriptor instead.
func (*LsOutput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{7}
}

func (x *LsOutput) GetListOfMachines() []string {
	if x != nil {
		return x.ListOfMachines
	}
	return nil
}

type StoreInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreInput) Reset() {
	*x = StoreInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInput) ProtoMessage() {}

func (x *StoreInput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInput.ProtoReflect.Descriptor instead.
func (*StoreInput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{8}
}

type StoreOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOfFiles []string `protobuf:"bytes,1,rep,name=listOfFiles,proto3" json:"listOfFiles,omitempty"`
}

func (x *StoreOutput) Reset() {
	*x = StoreOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOutput) ProtoMessage() {}

func (x *StoreOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOutput.ProtoReflect.Descriptor instead.
func (*StoreOutput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{9}
}

func (x *StoreOutput) GetListOfFiles() []string {
	if x != nil {
		return x.ListOfFiles
	}
	return nil
}

type GetNumVersionsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *GetNumVersionsInput) Reset() {
	*x = GetNumVersionsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumVersionsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumVersionsInput) ProtoMessage() {}

func (x *GetNumVersionsInput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumVersionsInput.ProtoReflect.Descriptor instead.
func (*GetNumVersionsInput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{10}
}

func (x *GetNumVersionsInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetNumVersionsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *GetNumVersionsOutput) Reset() {
	*x = GetNumVersionsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdfs_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumVersionsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumVersionsOutput) ProtoMessage() {}

func (x *GetNumVersionsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sdfs_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumVersionsOutput.ProtoReflect.Descriptor instead.
func (*GetNumVersionsOutput) Descriptor() ([]byte, []int) {
	return file_sdfs_server_proto_rawDescGZIP(), []int{11}
}

func (x *GetNumVersionsOutput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_sdfs_server_proto protoreflect.FileDescriptor

var file_sdfs_server_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x22, 0x3c, 0x0a, 0x08, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x25,
	0x0a, 0x09, 0x50, 0x75, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x28, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x09, 0x0a, 0x07, 0x4c, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x22, 0x32, 0x0a, 0x08, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x22, 0x2f, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x32, 0x8f, 0x03, 0x0a, 0x0a, 0x53, 0x64, 0x66, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x15, 0x2e, 0x73, 0x64, 0x66,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x16, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x75, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3f, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x16, 0x2e, 0x73,
	0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x33, 0x0a, 0x02, 0x4c, 0x73, 0x12, 0x14,
	0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x73, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x18, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4e, 0x75, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x2e,
	0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e,
	0x75, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x64, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x75, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x73, 0x64, 0x66, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdfs_server_proto_rawDescOnce sync.Once
	file_sdfs_server_proto_rawDescData = file_sdfs_server_proto_rawDesc
)

func file_sdfs_server_proto_rawDescGZIP() []byte {
	file_sdfs_server_proto_rawDescOnce.Do(func() {
		file_sdfs_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdfs_server_proto_rawDescData)
	})
	return file_sdfs_server_proto_rawDescData
}

var file_sdfs_server_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sdfs_server_proto_goTypes = []interface{}{
	(*PutInput)(nil),             // 0: sdfs_server.PutInput
	(*PutOutput)(nil),            // 1: sdfs_server.PutOutput
	(*DeleteInput)(nil),          // 2: sdfs_server.DeleteInput
	(*DeleteOutput)(nil),         // 3: sdfs_server.DeleteOutput
	(*GetInput)(nil),             // 4: sdfs_server.GetInput
	(*GetOutput)(nil),            // 5: sdfs_server.GetOutput
	(*LsInput)(nil),              // 6: sdfs_server.LsInput
	(*LsOutput)(nil),             // 7: sdfs_server.LsOutput
	(*StoreInput)(nil),           // 8: sdfs_server.StoreInput
	(*StoreOutput)(nil),          // 9: sdfs_server.StoreOutput
	(*GetNumVersionsInput)(nil),  // 10: sdfs_server.GetNumVersionsInput
	(*GetNumVersionsOutput)(nil), // 11: sdfs_server.GetNumVersionsOutput
}
var file_sdfs_server_proto_depIdxs = []int32{
	0,  // 0: sdfs_server.SdfsServer.Put:input_type -> sdfs_server.PutInput
	2,  // 1: sdfs_server.SdfsServer.Delete:input_type -> sdfs_server.DeleteInput
	4,  // 2: sdfs_server.SdfsServer.Get:input_type -> sdfs_server.GetInput
	6,  // 3: sdfs_server.SdfsServer.Ls:input_type -> sdfs_server.LsInput
	8,  // 4: sdfs_server.SdfsServer.Store:input_type -> sdfs_server.StoreInput
	10, // 5: sdfs_server.SdfsServer.GetNumVersions:input_type -> sdfs_server.GetNumVersionsInput
	1,  // 6: sdfs_server.SdfsServer.Put:output_type -> sdfs_server.PutOutput
	3,  // 7: sdfs_server.SdfsServer.Delete:output_type -> sdfs_server.DeleteOutput
	5,  // 8: sdfs_server.SdfsServer.Get:output_type -> sdfs_server.GetOutput
	7,  // 9: sdfs_server.SdfsServer.Ls:output_type -> sdfs_server.LsOutput
	9,  // 10: sdfs_server.SdfsServer.Store:output_type -> sdfs_server.StoreOutput
	11, // 11: sdfs_server.SdfsServer.GetNumVersions:output_type -> sdfs_server.GetNumVersionsOutput
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sdfs_server_proto_init() }
func file_sdfs_server_proto_init() {
	if File_sdfs_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdfs_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumVersionsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdfs_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumVersionsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdfs_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdfs_server_proto_goTypes,
		DependencyIndexes: file_sdfs_server_proto_depIdxs,
		MessageInfos:      file_sdfs_server_proto_msgTypes,
	}.Build()
	File_sdfs_server_proto = out.File
	file_sdfs_server_proto_rawDesc = nil
	file_sdfs_server_proto_goTypes = nil
	file_sdfs_server_proto_depIdxs = nil
}
